services:
  dispatcher-service:
    build:
      context: ..
      dockerfile: src/services/dispatcher-service/Dockerfile
    image: dispatcher-service
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
    depends_on:
      - authentication-service
      - project-service
      - agent-service
      - user-service
      - task-service
    networks:
      - internal
      - public

  authentication-service:
    build:
      context: ..
      dockerfile: src/services/authentication-service/Dockerfile
    image: authentication-service
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
    depends_on:
      - elasticsearch
    volumes:
      - ./keys:/app/keys:rw
      - ./dataprotection:/app/dataprotection:rw
    networks:
      - internal

  project-service:
    build:
      context: ..
      dockerfile: src/services/project-service/Dockerfile
    image: project-service
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
    depends_on:
      - mongodb
      - elasticsearch
      - message-broker
    networks:
      - internal

  task-service:
    build:
      context: ..
      dockerfile: src/services/task-service/Dockerfile
    image: task-service
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
    depends_on:
      - mongodb
      - elasticsearch
      - message-broker
      - project-service
    networks:
      - internal

  agent-service:
    build:
      context: ..
      dockerfile: src/services/ai_agent_service/Dockerfile
    image: agent-service
    command: uvicorn src.services.ai_agent_service.app:app --host 0.0.0.0 --port 5001
    depends_on:
      - mongodb
      - ollama
    networks:
      - internal

  user-service:
    build:
      context: ..
      dockerfile: src/services/user_service/Dockerfile
    image: user-service
    command: uvicorn src.services.user_service.main:app --host 0.0.0.0 --port 5002   --log-level info --access-log
    depends_on:
      - mongodb
    networks:
      - internal

  mongodb:
    image: mongo:7
    volumes:
      - mongodb_data:/data/db
    networks:
      - internal

  message-broker:
    image: rabbitmq:3.13-management
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    networks:
      - internal

  ollama:
    image: ollama/ollama:latest
    container_name: ollama
    volumes:
      - ollama_data:/root/.ollama
    restart: unless-stopped
    networks:
      - internal

  ollama-pull:
    image: ollama/ollama:latest
    depends_on:
      - ollama
    entrypoint:
      - /bin/sh
      - -c
      - |
        sleep 8
        OLLAMA_HOST=http://ollama:11434 ollama pull llama3.2
    volumes:
      - ollama_data:/root/.ollama
    networks:
      - internal

  elasticsearch:
    image: elasticsearch:9.3.2
    volumes:
      - elasticsearch_data:/usr/share/elasticsearch/data
    networks:
      - internal

  kibana:
    image: kibana:9.3.2
    networks:
      - internal
    depends_on:
      - elasticsearch

  filebeat:
    image: docker.elastic.co/beats/filebeat:8.13.0
    user: root
    command: ["filebeat", "-e", "--strict.perms=false"]
    volumes:
      - /var/lib/docker/containers:/var/lib/docker/containers:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./filebeat/filebeat.yml:/usr/share/filebeat/filebeat.yml:ro
    depends_on:
      - elasticsearch
    networks:
      - internal

  prometheus:
    image: prom/prometheus:latest
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/usr/share/prometheus/console_libraries'
      - '--web.console.templates=/usr/share/prometheus/consoles'
    networks:
      - internal

  grafana:
    image: grafana/grafana:latest
    volumes:
      - grafana_data:/var/lib/grafana
      - ./grafana/provisioning:/etc/grafana/provisioning
    depends_on:
      - prometheus
      - elasticsearch
      - influxdb
    networks:
      - internal

  influxdb:
    image: influxdb:1.8
    volumes:
      - influxdb_data:/var/lib/influxdb2
    networks:
      - internal

  k6:
    image: grafana/k6:latest
    volumes:
      - ./k6/scripts:/scripts
    networks:
      - internal
    depends_on:
      - influxdb
      - dispatcher-service
    command: run --out influxdb=http://influxdb:8086/k6 /scripts/load-test.js

volumes:
  mongodb_data:
  elasticsearch_data:
  ollama_data:
  prometheus_data:
  grafana_data:
  influxdb_data:
  rabbitmq_data:
  identity-keys:


networks:
  internal:
    driver: bridge
  public:
    driver: bridge
